name: akarasauraus
favicon: null
layout_spectrum: 0.8119318862445652
typography_spectrum: 0.45281836087815464
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#23282b'
    - '#e2d4cb'
    - '#c3b1a7'
    - '#9f9188'
    - '#7c736e'
  brandStrength: 0.25
  lightness: 0.2966499677859247
  saturation: 0.7049239221960306
  rhythmicContrast: 0.9082264653407037
purpose: []
