name: akarasauraus
favicon: null
layout_spectrum: 0.52677
typography_spectrum: 0.64357
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#23282b'
    - '#e2d4cb'
    - '#c3b1a7'
    - '#9f9188'
    - '#7c736e'
  brandStrength: 0.25
  lightness: 0.8125
  saturation: 0.875
  rhythmicContrast: 1
purpose: []
